const K={items:'st_items',reports:'st_reports',history:'st_history',theme:'st_theme',sound:'st_sound',page:'st_page',draft:'st_draft'};let items=JSON.parse(localStorage.getItem(K.items)||'[]'),reports=JSON.parse(localStorage.getItem(K.reports)||'[]'),history=JSON.parse(localStorage.getItem(K.history)||'[]');let editing=null;
const $=id=>document.getElementById(id);const save=()=>{localStorage.setItem(K.items,JSON.stringify(items));localStorage.setItem(K.reports,JSON.stringify(reports));localStorage.setItem(K.history,JSON.stringify(history));render()};
// The uploaded video contained a short click event around 0.94–1.10s. That isolated event is used here so the sound starts immediately on the tap.
const clickAudio=new Audio('click.mp3');clickAudio.preload='auto';clickAudio.volume=.85;let sound=localStorage.getItem(K.sound)!=='off';function clickSound(){if(!sound)return;try{clickAudio.pause();clickAudio.currentTime=0;const p=clickAudio.play();if(p)p.catch(()=>{});}catch(e){}}
document.addEventListener('pointerdown',e=>{if(e.target.closest('button,.fileBtn'))clickSound()},{capture:true});
function nav(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));if($(id))$(id).classList.add('active');localStorage.setItem(K.page,id);window.scrollTo(0,0);render()}
// Recovery: remember the current SchoolTrack page so an accidental refresh/reopen does not reset the app.
function restorePage(){const id=localStorage.getItem(K.page)||'dashboard';if($(id))$(id).classList.add('active');else $('dashboard').classList.add('active')}
restorePage();
// Android/browser Back: stay inside SchoolTrack instead of leaving the app on the first Back press.
let backArmed=false;window.addEventListener('popstate',()=>{backArmed=false;const id=localStorage.getItem(K.page)||'dashboard';if($(id))$(id).classList.add('active')});history.replaceState({schooltrack:true},'',location.href);window.addEventListener('popstate',()=>{history.pushState({schooltrack:true},'',location.href);if(!backArmed){backArmed=true;setTimeout(()=>backArmed=false,1800);return;}nav('dashboard');backArmed=false});document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)nav(b.dataset.go)});
$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(K.theme,document.body.classList.contains('dark')?'dark':'light');$('themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'};if(localStorage.getItem(K.theme)==='dark'){document.body.classList.add('dark');$('themeBtn').textContent='☀️'}
['itemId','itemName','category','quantity','quality','condition','location','responsible','remarks'].forEach(id=>$(id).addEventListener('input',()=>{localStorage.setItem(K.draft,JSON.stringify(Object.fromEntries(['itemId','itemName','category','quantity','quality','condition','location','responsible','remarks'].map(k=>[k,$(k).value]))))}));
function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(K.draft)||'null');if(!d)return;Object.entries(d).forEach(([k,v])=>{if($(k)&&!$(k).value)$(k).value=v})}catch(e){}}
restoreDraft();
$('itemForm').onsubmit=e=>{e.preventDefault();const id=$('itemId').value.trim();let q=Math.max(1,+$('quantity').value||1);if(!editing&&items.some(x=>x.id===id)){alert('Item ID already exists.');return}if(editing){const x=items.find(x=>x.id===editing);Object.assign(x,{name:$('itemName').value,category:$('category').value,qty:q,quality:$('quality').value,condition:$('condition').value,location:$('location').value,responsible:$('responsible').value,remarks:$('remarks').value});history.unshift(`Edited ${x.name}`)}else{const x={id,name:$('itemName').value,category:$('category').value,qty:q,available:q,borrowed:0,repair:0,missing:0,quality:$('quality').value,condition:$('condition').value,location:$('location').value,responsible:$('responsible').value,remarks:$('remarks').value};items.push(x);history.unshift(`Added ${x.name}`)}editing=null;e.target.reset();$('itemId').disabled=false;localStorage.removeItem(K.draft);$('formTitle').textContent='➕ Add Item';save();nav('inventory')};
function fill(x){editing=x.id;$('formTitle').textContent='✏️ Edit Item';$('itemId').value=x.id;$('itemId').disabled=true;[['itemName','name'],['category','category'],['quantity','qty'],['quality','quality'],['condition','condition'],['location','location'],['responsible','responsible'],['remarks','remarks']].forEach(([a,b])=>$(a).value=x[b]);nav('add')}
function act(id,type){const x=items.find(x=>x.id===id);if(!x)return;if(type==='borrow'&&x.available>0){x.available--;x.borrowed++;history.unshift(`Borrowed ${x.name}`)}else if(type==='return'&&x.borrowed>0){x.borrowed--;x.available++;history.unshift(`Returned ${x.name}`)}else if(type==='repair'&&x.available>0){x.available--;x.repair++;history.unshift(`Sent ${x.name} to repair`)}else if(type==='complete'&&x.repair>0){x.repair--;x.available++;history.unshift(`Completed repair: ${x.name}`)}else if(type==='missing'&&x.available>0){x.available--;x.missing++;history.unshift(`Marked missing: ${x.name}`)}else if(type==='found'&&x.missing>0){x.missing--;x.available++;history.unshift(`Found: ${x.name}`)}else if(type==='delete'){if(confirm('Delete this item?')){items=items.filter(i=>i.id!==id);history.unshift(`Deleted ${x.name}`)}}else{alert('That action is not available right now.')}save()}
function render(){let total=items.reduce((s,x)=>s+x.qty,0),a=items.reduce((s,x)=>s+x.available,0),b=items.reduce((s,x)=>s+x.borrowed,0),r=items.reduce((s,x)=>s+x.repair,0),m=items.reduce((s,x)=>s+x.missing,0);$('total').textContent=total;$('available').textContent=a;$('borrowed').textContent=b;$('repair').textContent=r;$('missing').textContent=m;$('stockText').textContent=total===0?'Out of stock':a===0?'Out of stock':a<=5?'Low stocks':'In stocks';let q=($('search').value||'').toLowerCase();let list=items.filter(x=>[x.id,x.name,x.category,x.location,x.responsible].join(' ').toLowerCase().includes(q));$('inventoryList').innerHTML=list.length?list.map(x=>`<div class="item"><div class="itemTop"><div><div class="itemName">${x.name}</div><span class="tag">${x.category}</span></div><b>${x.available}/${x.qty}</b></div><div class="meta">ID: ${x.id} · ${x.quality} · ${x.condition}<br>📍 ${x.location} · 👤 ${x.responsible}</div><div class="actions"><button onclick="act('${x.id}','borrow')">Borrow</button><button onclick="act('${x.id}','return')">Return</button><button onclick="act('${x.id}','repair')">Repair</button><button onclick="act('${x.id}','complete')">Complete</button><button onclick="act('${x.id}','missing')">Missing</button><button onclick="act('${x.id}','found')">Found</button><button onclick="fill(items.find(i=>i.id==='${x.id}'))">Edit</button><button onclick="act('${x.id}','delete')">Delete</button></div></div>`).join(''):'<div class="empty">No inventory items yet.</div>';renderReports();renderHistory()}
function renderReports(){$('reportsList').innerHTML=reports.length?reports.map((r,i)=>`<div class="report"><strong>${r.item}</strong><div>${r.problem}</div><small>${r.status} · ${r.date}</small><div class="actions"><button onclick="reportStatus(${i},'Pending')">Pending</button><button onclick="reportStatus(${i},'Under Review')">Under Review</button><button onclick="reportStatus(${i},'Resolved')">Resolved</button></div></div>`).join(''):'<div class="empty">No reports yet.</div>'}function reportStatus(i,s){reports[i].status=s;history.unshift(`Report ${s}: ${reports[i].item}`);save()}$('newReport').onclick=()=>{const item=prompt('Item name?');if(!item)return;const problem=prompt('Problem?');if(!problem)return;reports.unshift({item,problem,status:'Pending',date:new Date().toLocaleDateString()});save()};
function renderHistory(){$('historyList').innerHTML=history.slice(0,80).map(x=>`<div class="history"><small>${x}</small></div>`).join('')||'<div class="empty">No transactions yet.</div>'}$('search').oninput=render;$('backup').onclick=()=>{const blob=new Blob([JSON.stringify({items,reports,history},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SchoolTrack-Backup.json';a.click()};$('restore').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);items=d.items||[];reports=d.reports||[];history=d.history||[];save();alert('Backup restored.')}catch{alert('Invalid backup file.')}};rd.readAsText(f)};$('csv').onclick=()=>{const rows=[['ID','Name','Category','Quantity','Available','Borrowed','Repair','Missing','Quality','Condition','Location','Responsible']].concat(items.map(x=>[x.id,x.name,x.category,x.qty,x.available,x.borrowed,x.repair,x.missing,x.quality,x.condition,x.location,x.responsible]));const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='SchoolTrack-Inventory.csv';a.click()};$('clear').onclick=()=>{if(confirm('Clear all SchoolTrack data?')){items=[];reports=[];history=[];save()}};render();
